// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"database/sql"
	"time"
)

type Espacio struct {
	ID             string
	ParqueaderoID  string
	Numero         string
	Disponible     bool
	ReservadoHasta sql.NullTime
}

type Ocupacione struct {
	ID        string
	EspacioID string
	Placa     string
	Entrada   time.Time
	Salida    sql.NullTime
	Activa    bool
}

type Parqueadero struct {
	ID        string
	Nombre    string
	Ubicacion string
	Capacidad int64
	Activo    bool
}
