// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcdb

import (
	"context"
)

const crearParqueadero = `-- name: CrearParqueadero :exec
INSERT INTO parqueaderos (
    id,
    nombre,
    ubicacion,
    capacidad,
    activo
)
VALUES (?, ?, ?, ?, ?)
`

type CrearParqueaderoParams struct {
	ID        string
	Nombre    string
	Ubicacion string
	Capacidad int64
	Activo    bool
}

func (q *Queries) CrearParqueadero(ctx context.Context, arg CrearParqueaderoParams) error {
	_, err := q.db.ExecContext(ctx, crearParqueadero,
		arg.ID,
		arg.Nombre,
		arg.Ubicacion,
		arg.Capacidad,
		arg.Activo,
	)
	return err
}

const eliminarParqueadero = `-- name: EliminarParqueadero :exec
DELETE FROM parqueaderos
WHERE id = ?
`

func (q *Queries) EliminarParqueadero(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, eliminarParqueadero, id)
	return err
}

const listarEspacios = `-- name: ListarEspacios :many
SELECT id, parqueadero_id, numero, disponible, reservado_hasta FROM espacios
`

func (q *Queries) ListarEspacios(ctx context.Context) ([]Espacio, error) {
	rows, err := q.db.QueryContext(ctx, listarEspacios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Espacio
	for rows.Next() {
		var i Espacio
		if err := rows.Scan(
			&i.ID,
			&i.ParqueaderoID,
			&i.Numero,
			&i.Disponible,
			&i.ReservadoHasta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarParqueaderos = `-- name: ListarParqueaderos :many
SELECT id, nombre, ubicacion, capacidad, activo FROM parqueaderos
`

func (q *Queries) ListarParqueaderos(ctx context.Context) ([]Parqueadero, error) {
	rows, err := q.db.QueryContext(ctx, listarParqueaderos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Parqueadero
	for rows.Next() {
		var i Parqueadero
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Ubicacion,
			&i.Capacidad,
			&i.Activo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerParqueadero = `-- name: ObtenerParqueadero :one
SELECT id, nombre, ubicacion, capacidad, activo FROM parqueaderos
WHERE id = ?
`

func (q *Queries) ObtenerParqueadero(ctx context.Context, id string) (Parqueadero, error) {
	row := q.db.QueryRowContext(ctx, obtenerParqueadero, id)
	var i Parqueadero
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Ubicacion,
		&i.Capacidad,
		&i.Activo,
	)
	return i, err
}
